<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 9px;
            color: #333;
            padding: 16px;
        }
        h1 {
            font-size: 18px;
            color: #dc3545;
            text-align: center;
            margin-bottom: 6px;
        }
        .header-info {
            font-size: 8px;
            color: #666;
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 8px;
        }
        .table th {
            background-color: #dc3545;
            color: white;
            padding: 6px 4px;
            text-align: left;
            border: 1px solid #dc3545;
        }
        .table td {
            padding: 5px 4px;
            border: 1px solid #ccc;
        }
        .footer {
            margin-top: 20px;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .footer-grid {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h1>{{ $title ?? 'System Logs Report' }}</h1>

    <div class="header-info">
        <div>Generated: {{ $exportDate->format('F d, Y g:i A') }}</div>
        <div>Total Logs: {{ $totalItems }}</div>
        <div>Report ID: LOG-{{ $exportDate->format('Ymd-His') }}</div>
    </div>

    @if ($logs->isEmpty())
        <p style="font-size: 9px;">No history logs available.</p>
    @else
        <table class="table">
            <thead>
                <tr>
                    <th style="width: 15%;">Staff Name</th>
                    <th style="width: 10%;">Action</th>
                    <th style="width: 18%;">Equipment</th>
                    <th style="width: 10%;">Status</th>
                    <th style="width: 15%;">Model/Brand</th>
                    <th style="width: 22%;">Description</th>
                    <th style="width: 10%;">Action Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($logs as $log)
                <tr>
                    <td>{{ $log->staff->name ?? 'N/A' }}</td>
                    <td>{{ $log->action }}</td>
                    <td>{{ $log->equipment->equipment_name ?? 'N/A' }}</td>
                    <td>{{ ucfirst($log->equipment->status ?? 'N/A') }}</td>
                    <td>{{ $log->model_brand ?? 'N/A' }}</td>
                    <td>{{ $log->description ?? 'N/A' }}</td>
                    <td>{{ \Carbon\Carbon::parse($log->action_date)->format('M d, Y H:i') }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        <div class="footer-grid">
            <div>
                <strong>Total Logs:</strong> {{ $totalItems }}<br>
                <strong>Generated by:</strong> UPITDC Inventory System
            </div>
            <div>
                <strong>Report Date:</strong> {{ $exportDate->format('F d, Y') }}<br>
                <strong>Status:</strong> As of {{ $exportDate->format('g:i A') }}
            </div>
        </div>
        <hr style="margin: 6px 0; border: none; border-top: 1px solid #ddd;">
        <div style="text-align: center;">
            © {{ date('Y') }} University of the Philippines Diliman Information Technology Development Center<br>
            <p>This report was automatically generated by the Inventory Management System</p>
        </div>
    </div>
</body>
</html>
