<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 9px;
            color: #333;
            padding: 16px;
        }
        h1 {
            font-size: 18px;
            color: #dc3545;
            text-align: center;
            margin-bottom: 8px;
        }
        .header-info {
            font-size: 8px;
            color: #666;
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            font-size: 8px;
        }
        .table th {
            background-color: #dc3545;
            color: white;
            padding: 6px 4px;
            text-align: left;
            border: 1px solid #dc3545;
        }
        .table td {
            padding: 5px 4px;
            border: 1px solid #ccc;
        }
        .footer {
            margin-top: 20px;
            font-size: 8px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .footer-grid {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h1>{{ $title ?? 'UPITDC Staff Report' }}</h1>

    <div class="header-info">
        <div>Generated: {{ $exportDate->format('F d, Y g:i A') }}</div>
        <div>Total Staff: {{ $totalStaff }}</div>
        <div>Report ID: ST-{{ $exportDate->format('Ymd-His') }}</div>
    </div>

    <h3 style="font-size: 11px; font-weight: bold; margin-bottom: 6px;">Staff List</h3>
    <table class="table">
        <thead>
            <tr>
                <th style="width: 5%;">ID</th>
                <th style="width: 20%;">Name</th>
                <th style="width: 25%;">Department</th>
                <th style="width: 25%;">Email</th>
                <th style="width: 10%;">Status</th>
                <th style="width: 15%;">Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach($staffList as $staff)
            <tr>
                <td>{{ $staff->id }}</td>
                <td>{{ $staff->name }}</td>
               <td>{{ $staff->department ?? 'N/A' }}</td>
                <td>{{ $staff->email }}</td>
                <td>{{ ucfirst($staff->status) }}</td>
                <td>{{ $staff->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div class="footer-grid">
            <div>
                <strong>Total Staff:</strong> {{ $totalStaff }}<br>
                <strong>Active Staff:</strong> {{ $staffList->where('status', 'active')->count() }}
            </div>
            <div>
                <strong>Generated by:</strong> UPITDC Inventory Management System<br>
                <strong>Date:</strong> {{ $exportDate->format('M d, Y') }}
            </div>
            <div>
                <strong>Report Type:</strong> Staff Masterlist<br>
                <strong>Status:</strong> As of {{ $exportDate->format('g:i A') }}
            </div>
        </div>
        <hr style="margin: 8px 0; border: none; border-top: 1px solid #ddd;">
        <div style="text-align: center;">
            © {{ date('Y') }} University of the Philippines Diliman Information Technology Development Center<br>
        </div>
    </div>
</body>
</html>